### PR TITLE
alerts: reduce severity of CPUThrottlingHigh alert

### PR DESCRIPTION
**Pull request by paulfantom**
Reducing alert severity as per https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/108#issuecomment-651711524

### CODE REVIEW

**Comment by simonpasquier** [comment]
lgtm

**Comment by metalmatze** [comment]
Let's wait for a couple of more eyes on this. :blush:

**Comment by snowcrumble** [comment]
lgtm

**Comment by chiluk** [comment]
Dropping this to info looks good to me.  I really think there should be a way to mute this monitor though for cpu bound applications that will almost always hit the limit.  Perhaps this could be done via a pod annotation?

**Comment by brancz** [comment]
Info severity should be inhibited if it is not accompanied by a warning or critical severity alert, so it shouldn't ever produce noise on its own.

**Comment by povilasv** [comment]
merging this, muting can be discussed in seperate github issue or slack channels.

**Pull request merged**
