### PR TITLE
dashboards: Fix node dashboard legend

### PR DESCRIPTION
**Pull request by brancz**
#49 broke the dashboard build, this fixes it. This just moves the items from the `legend` object to the "top level" parameters and prefixes them correctly as grafonnet requires it.

@tomwilkie @metalmatze 

cc @mrsiano

### CODE REVIEW

**Comment by tomwilkie** [comment]
LGTM!  They broke when loaded into grafana?

**Comment by brancz** [comment]
No it simply didn’t compile. Now that you say it though I wonder why the build here didn’t fail.

**Comment by tomwilkie** [comment]
That’s what I was wondering...

**Comment by brancz** [comment]
I’ll investigate a bit and see why. This shouldn’t happen again...

**Comment by brancz** [comment]
As this is currently a broken dependency I will merge this, should there still be a problem, then I will follow up with another PR, but with all my testing this looks good now.

**Pull request merged**
