### PR TITLE
Override timezone on all dashboards to default

### LINKED ISSUE #77: change all grafana dashboards timezone to default
Have all the dashboards use the local browser default timezone - not UTC.

Resolves the comments on the following issue about setting the timezone for the grafana web ui: https://github.com/coreos/prometheus-operator/issues/1807

### PR DESCRIPTION
**Pull request by metalmatze**
Due to grafana-builder not allowing to set the timezone on dashboard creation, we not simply override all dashboards' timezone in the for loop when setting the uid.
Maybe we should rename the `add-dashboard-uid.libsonnet`?

Fixes #77 

@brancz @tomwilkie

### CODE REVIEW

**Comment by brancz** [comment]
Agreed, we should rename the file. Maybe `defaults.jsonnet`?

**Comment by metalmatze** [comment]
Renamed to `defaults.libsonnet`. Is the approach of overriding fine? Merge?

**Comment by brancz** [comment]
Is the value `"default"`? I thought it was empty string.

**Comment by metalmatze** [comment]
Whoops. I couldn't find something quickly. I'll double check tomorrow!

**Comment by metalmatze** [comment]
You were right! 👍 
I removed the timezone from one of my dashboards in the UI and then saw an empty string in the JSON model that Grafana exposes. I've updated the PR accordingly.

**Comment by brancz** [comment]
lgtm :+1:

**Pull request merged**
