### PR TITLE
Use kube_node_status_capacity_pods for pod capacity alert.

### PR DESCRIPTION
**Pull request by tomwilkie**
Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>

### CODE REVIEW

**Comment by metalmatze** [comment]
Did you run this query against a Prometheus?
I think the node labels still mismatch as one of them contains the ports and the other doesn't.

screenshot from 2019-01-09 10-01-43

**Comment by tomwilkie** [comment]
@metalmatze it worked with my relabeling rules on GKE!  But good catch.  Lets see if I can find a better way of doing the join.

**Comment by tomwilkie** [comment]
Can't see a way, so I've make an upstream issue.  If that gets positive response I'll put together a PR.

**Comment by tomwilkie** [comment]
See https://github.com/kubernetes/kubernetes/pull/72910

**Comment by brancz** [comment]
The `kube_node_name` metric has been merged, so we can proceed here. As this metric is only available in 1.14, we should go with a similar strategy as https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/182

**Pull request closed without merging**
