### PR TITLE
Minor improvements to API server dashboard

### PR DESCRIPTION
**Pull request by lnovara**
This PR improves the API server dashboard by adding minimums to Y-axis of every plot and moving the singlestat panel on its own row to give the dashboard a more homogeneous structure.

### CODE REVIEW

**Comment by brancz** [comment]
cc @povilasv

**Comment by lnovara** [comment]
@brancz @povilasv There are also other minor issues like these in the other dashboards, do you want me to address them in separate PRs or we can pack everythin into this one?

Thank you.

**Comment by brancz** [comment]
I'd say let's do small separate PRs. Also it would help immensely if you could attach a screenshot of before after, if it's not too much trouble :)

**Comment by lnovara** [comment]
Thank you @brancz, I will open other PRs.

Meanwhile, here you have the before and after screenshots of the dashboard:

Before:



After:

**Comment by povilasv** [comment]
I'm not sure whether it makes sense to make `up` have a separate row, as those dashboards are quite a long already. 

Other changes LGTM

**Comment by brancz** [comment]
Agreed regarding the up panel.

**Pull request closed without merging**
