### PR TITLE
Add Apache 2.0 license.

### PR DESCRIPTION
**Pull request by tomwilkie**
Need LGTMs from ~@brancz~, ~@StevenACoffman~, ~@adamdecaf~, @dimm0, ~@metalmatze~, ~@richerve~ 

Thanks!

Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>

### CODE REVIEW

**Comment by metalmatze** [comment]
LGTM

**Comment by StevenACoffman** [comment]
LGTM

**Comment by brancz** [comment]
LGTM

**Comment by richerve** [comment]
Not much to add, LGTM

**Comment by adamdecaf** [comment]
LGTM

**Comment by tomwilkie** [comment]
ping @dimm0?  Let me know if this is a problem.

**Comment by dimm0** [comment]
LGTM

**Comment by tomwilkie** [comment]
Excellent, thanks!

**Pull request merged**
