### PR TITLE
fix cpu utilization query in cluster resources dashboards

### PR DESCRIPTION
**Pull request by ravilr**
fix the issue introduced in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/667#discussion_r742629004

@paulfantom @julianwiedmann

### CODE REVIEW

**Comment by julianwiedmann** [comment]
thanks @ravilr !

I'd want to re-assure myself that your `sum-of-avgs-of-rate` is the same as my expected `avg-of-sum-of-rates` ... but that's too likely much math headaches for a Friday.

**Comment by paulfantom** [comment]
FYI, I tested that before merging ;)

**Comment by julianwiedmann** [comment]
> > I'd want to re-assure myself that your sum-of-avgs-of-rate is the same as my expected avg-of-sum-of-rates
> 
> FYI, I tested that before merging ;)

and I did the same just now as an act of penance :)

**Comment by julianwiedmann** [comment]
> > I'd want to re-assure myself that your sum-of-avgs-of-rate is the same as my expected avg-of-sum-of-rates
> 
> FYI, I tested that before merging ;)

and I did the same just now as an act of penance :)

**Pull request merged**
