### PR TITLE
Fix queries to use cluster label

### PR DESCRIPTION
**Pull request by semekh**
Fix queries to use cluster label when necessary.

### CODE REVIEW

**Comment by sc250024** [comment]
@SeMeKh thanks for this fix!

**Comment by sc250024** [comment]
@csmarchbanks Yes, that would be of interest. We use local Prometheus instances to do the scraping within Kubernetes, but all of our metrics are being sent to one instance on Grafana Cloud. Currently we observe the same as you, where the dashboards don't fully support multi-cluster.

**Comment by csmarchbanks** [comment]
@SeMeKh is there a reason you left the rules such as `node_namespace_pod_container:container_memory_working_set_bytes` to not be split by cluster label as well?

**Comment by skl** [comment]
This seems to be no longer relevant - the current apps recording rules are using the cluster label atm, closing.

**Pull request closed without merging**
