### PR TITLE
fix template query in node resources dashboard

### PR DESCRIPTION
**Pull request by ravilr**
Fix regression introduced in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/669#discussion_r742634559

@paulfantom

### CODE REVIEW

**Comment by paulfantom** [comment]
LGMT, but I would like to know @discordianfish opinion on this.

**Comment by discordianfish** [comment]
Ah good catch.. It's really hard to validate these. Would be great to have some sort of tests for the dashboards.
Not sure about this solution though.`kube_pod_info` comes from ksm as well. There is one per pod but they all come from the same node, right?
Ideally we use a metric here that has one timeseries per node. So some something that runs on all nodes like up{job="kubelet"} (or node-exporter), right?

**Comment by paulfantom** [comment]
We can use `kube_node_info` :)

**Comment by ravilr** [comment]
updated to use `kube_node_info`. PTAL.

**Pull request merged**
