### PR TITLE
Add unschedulable alert

### PR DESCRIPTION
**Pull request by xonvanetta**
Signed-off-by: Fabian Heib <11271952+xonvanetta@users.noreply.github.com>

### CODE REVIEW

**Review by paulfantom — CHANGES_REQUESTED** [review]
This alert in the proposed form would fire if any node is cordoned and as such, it would be very noisy. Especially considering it would alert just after 15m since the node was cordoned. 

Personally, I have baremetal nodes that can take more than that amount of time just to do a full cycle of `cordon-drain-reboot-uncordon`

**Comment by xonvanetta** [comment]
There is a use case that's weird and won't work good with masters without taints and are cordoned instead.

Still made this PR to have a discussion about it

**Comment by paulfantom** [comment]
> There is a use case that's weird and won't work good with masters without taints and are cordoned instead.

That sounds like a very specific use-case. Could you describe it in detail?

**Comment by xonvanetta** [comment]
> That sounds like a very specific use-case. Could you describe it in detail?

If you setup a cluster and forgot/don't taint the control-plane but instead cordon the control-plane nodes this would also trigger alerts. 

> This alert in the proposed form would fire if any node is cordoned and as such, it would be very noisy. Especially considering it > would alert just after 15m since the node was cordoned.
>
> Personally, I have baremetal nodes that can take more than that amount of time just to do a full cycle of cordon-drain-reboot-uncordon

Any good suggestion for a duration? We currently aim have less then 15m for a full cycle
But we also noted some updates takes longer than 1h

**Comment by paulfantom** [comment]
So if I understand you correctly you need this only for the control plane nodes and only in case some of your configurations weren't correctly applied? For such a case, I don't think having a generic `KubeNodeUnschedulable` alert is a way to go, especially since there are multiple scenarios where a cordoned node is not a case for an alert.

From what I can see you want to create a cause-based alert to prevent one particular misconfiguration. IMHO this is not a good way to create alerts and it goes against [prometheus alerting best practices](https://prometheus.io/docs/practices/alerting/). 

On top of that, the problem you described would be caught by the `KubeContainerWaiting` alert (which in this case is symptomatic) when pods are rolled on control plane nodes.

**Comment by xonvanetta** [comment]
Our use case was actually that we forgot to uncordon some nodes after some work and maintenance was done and I thought why isn't this really an alert. Got a suggestion for the for or would 1h be good enough?

The case i described was more of an edge case that this PR causes harm for, if it is a problem or just something to forget and not think about. 

Sorry if it wasn't clear enough

**Comment by xonvanetta** [comment]
I did read the best practices for alerting and agree that most symptoms would be caught by `KubeContainerWaiting` or other alerts like `KubeletTooManyPods`, `KubeNodeUnreachable` but I would also like to see an alert for `KubeNodeUnschedulable` as this would be a part of the symptoms causing the other alerts. But maybe alert on it first after `1h`.

Our use case was that there were worker nodes that were forgotten to uncordon, it didn't cause us any harm yet there were cordoned for a week, if more workers nodes would be cordon it would be problematic .

The case i described before was just something i thought would be an issue for this PR and should be forgotten as other alerts would have been firing.

If this still doesn't fit here we can close this PR, what do you think about it @paulfantom

**Comment by paulfantom** [comment]
I am not 100% convinced this alert should be merged, but I won't be blocking if other maintainers wish to see it merged. However, I would like to see this with a very long delay (something like `for: 24h`) to limit potential false positives.

ping @metalmatze @povilasv

**Comment by povilasv** [comment]
This one is tricky if node is unscheduleable for too long you want to get alerted, but how long is too long :D

You are missing `%(kubeStateMetricsSelector)s` selector.

I think 24h might be a good initial value, if this doesn't work we can always modify or remove.

**Pull request closed without merging**
