### PR TITLE
Switch to github actions

### PR DESCRIPTION
**Pull request by arajkumar**
This PR switches the CI workflow to GH actions.

### CODE REVIEW

**Comment by paulfantom** [comment]
I don't mind migrating to GH actions, but what are the benefits of this migration?

**Comment by arajkumar** [comment]
> I don't mind migrating to GH actions, but what are the benefits of this migration?

No real difference, but I thought of refactoring the single monolithic verification job(make all) into 3 parallel jobs(make test, make fmt, make lint) along with additional platform support(macOS & Linux). Anyways this would need quite a few modifications to cicleci config, IMHO using GH actions would simplify this.

**Review by paulfantom — APPROVED** [review]
lgtm

**Comment by arajkumar** [comment]
Hello @povilasv, Do you have any concern regarding this change?

**Review by povilasv — APPROVED** [review]
Nope, LGTM, I like both CIs :)

**Pull request merged**
