### PR TITLE
add alert for Pending or Failed PersistentVolumes

### PR DESCRIPTION
**Pull request by nrobert13**

### CODE REVIEW

**Comment by adamdecaf** [comment]
@nrobert13 Could you fix the syntax error?

> STATIC ERROR: ./alerts/storage_alerts.libsonnet:41:13-18: expected a comma before next field.

**Comment by nrobert13** [comment]
@adamdecaf , done.

**Comment by metalmatze** [comment]
If we want that alert, then it LGTM 👍

**Comment by nrobert13** [comment]
is this PR considered for merge, or should I just close it?

**Comment by cbeneke** [comment]
critical (as in 'propably a mail') Error for 1 minute pending is quite trigger friendly, I would suggest to split failed and pending or just increase the for value to at least 5m

**Comment by metalmatze** [comment]
Yup. Increasing to 5m seems good to me.

**Comment by nrobert13** [comment]
increased.

**Comment by cbeneke** [comment]
Hey, sorry that I missed that before, please include the selection labels.

```diff
            expr: |||
-              kube_persistentvolume_status_phase{phase=~"Failed|Pending"} > 0
-            |||,
+              kube_persistentvolume_status_phase{phase=~"Failed|Pending",%(prefixedNamespaceSelector)s%(kubeStateMetricsSelector)s} > 0
+            ||| % $._config,
```

when thats fixed, LGTM^^

**Comment by nrobert13** [comment]
updated

**Pull request merged**
