### PR TITLE
Introduce apiserver SLO of 99% with multiple burn rate alerts

### PR DESCRIPTION
**Pull request by metalmatze**
I want to start a discussion on having a SLO for the apiserver and its error rate.
By default I simply settled for 99% availability and generated all the recording rules and alerts for multi burn rate alerts.

/cc @brancz @csmarchbanks @tomwilkie @gouthamve @povilasv 

Here's the output for the generated rules as a reference.

```yaml
"groups":
- "name": "kube-apiserver-error"
  "rules":
  - "alert": "ErrorBudgetBurn"
    "annotations":
      "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-errorbudgetburn"
    "expr": |
      (
        status_class_5xx:apiserver_request_total:ratio_rate1h{job="kube-apiserver"} > (14.4*0.010000)
        and
        status_class_5xx:apiserver_request_total:ratio_rate5m{job="kube-apiserver"} > (14.4*0.010000)
      )
      or
      (
        status_class_5xx:apiserver_request_total:ratio_rate6h{job="kube-apiserver"} > (6*0.010000)
        and
        status_class_5xx:apiserver_request_total:ratio_rate30m{job="kube-apiserver"} > (6*0.010000)
      )
    "labels":
      "job": "kube-apiserver"
      "severity": "critical"
  - "alert": "ErrorBudgetBurn"
    "annotations":
      "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-errorbudgetburn"
    "expr": |
      (
        status_class_5xx:apiserver_request_total:ratio_rate1d{job="kube-apiserver"} > (3*0.010000)
        and
        status_class_5xx:apiserver_request_total:ratio_rate2h{job="kube-apiserver"} > (3*0.010000)
      )
      or
      (
        status_class_5xx:apiserver_request_total:ratio_rate3d{job="kube-apiserver"} > (0.010000)
        and
        status_class_5xx:apiserver_request_total:ratio_rate6h{job="kube-apiserver"} > (0.010000)
      )
    "labels":
      "job": "kube-apiserver"
      "severity": "warning"
  - "expr": |
      sum by (status_class) (
        label_replace(
          rate(apiserver_request_total{job="kube-apiserver"}[5m]
        ), "status_class", "${1}xx", "code", "([0-9])..")
      )
    "labels":
      "job": "kube-apiserver"
    "record": "status_class:apiserver_request_total:rate5m"
  - "expr": |
      sum by (status_class) (
        label_replace(
          rate(apiserver_request_total{job="kube-apiserver"}[30m]
        ), "status_class", "${1}xx", "code", "([0-9])..")
      )
    "labels":
      "job": "kube-apiserver"
    "record": "status_class:apiserver_request_total:rate30m"
  - "expr": |
      sum by (status_class) (
        label_replace(
          rate(apiserver_request_total{job="kube-apiserver"}[1h]
        ), "status_class", "${1}xx", "code", "([0-9])..")
      )
    "labels":
      "job": "kube-apiserver"
    "record": "status_class:apiserver_request_total:rate1h"
  - "expr": |
      sum by (status_class) (
        label_replace(
          rate(apiserver_request_total{job="kube-apiserver"}[2h]
        ), "status_class", "${1}xx", "code", "([0-9])..")
      )
    "labels":
      "job": "kube-apiserver"
    "record": "status_class:apiserver_request_total:rate2h"
  - "expr": |
      sum by (status_class) (
        label_replace(
          rate(apiserver_request_total{job="kube-apiserver"}[6h]
        ), "status_class", "${1}xx", "code", "([0-9])..")
      )
    "labels":
      "job": "kube-apiserver"
    "record": "status_class:apiserver_request_total:rate6h"
  - "expr": |
      sum by (status_class) (
        label_replace(
          rate(apiserver_request_total{job="kube-apiserver"}[1d]
        ), "status_class", "${1}xx", "code", "([0-9])..")
      )
    "labels":
      "job": "kube-apiserver"
    "record": "status_class:apiserver_request_total:rate1d"
  - "expr": |
      sum by (status_class) (
        label_replace(
          rate(apiserver_request_total{job="kube-apiserver"}[3d]
        ), "status_class", "${1}xx", "code", "([0-9])..")
      )
    "labels":
      "job": "kube-apiserver"
    "record": "status_class:apiserver_request_total:rate3d"
  - "expr": |
      sum(status_class:apiserver_request_total:rate5m{job="kube-apiserver",status_class="5xx"})
      /
      sum(status_class:apiserver_request_total:rate5m{job="kube-apiserver"})
    "labels":
      "job": "kube-apiserver"
    "record": "status_class_5xx:apiserver_request_total:ratio_rate5m"
  - "expr": |
      sum(status_class:apiserver_request_total:rate30m{job="kube-apiserver",status_class="5xx"})
      /
      sum(status_class:apiserver_request_total:rate30m{job="kube-apiserver"})
    "labels":
      "job": "kube-apiserver"
    "record": "status_class_5xx:apiserver_request_total:ratio_rate30m"
  - "expr": |
      sum(status_class:apiserver_request_total:rate1h{job="kube-apiserver",status_class="5xx"})
      /
      sum(status_class:apiserver_request_total:rate1h{job="kube-apiserver"})
    "labels":
      "job": "kube-apiserver"
    "record": "status_class_5xx:apiserver_request_total:ratio_rate1h"
  - "expr": |
      sum(status_class:apiserver_request_total:rate2h{job="kube-apiserver",status_class="5xx"})
      /
      sum(status_class:apiserver_request_total:rate2h{job="kube-apiserver"})
    "labels":
      "job": "kube-apiserver"
    "record": "status_class_5xx:apiserver_request_total:ratio_rate2h"
  - "expr": |
      sum(status_class:apiserver_request_total:rate6h{job="kube-apiserver",status_class="5xx"})
      /
      sum(status_class:apiserver_request_total:rate6h{job="kube-apiserver"})
    "labels":
      "job": "kube-apiserver"
    "record": "status_class_5xx:apiserver_request_total:ratio_rate6h"
  - "expr": |
      sum(status_class:apiserver_request_total:rate1d{job="kube-apiserver",status_class="5xx"})
      /
      sum(status_class:apiserver_request_total:rate1d{job="kube-apiserver"})
    "labels":
      "job": "kube-apiserver"
    "record": "status_class_5xx:apiserver_request_total:ratio_rate1d"
  - "expr": |
      sum(status_class:apiserver_request_total:rate3d{job="kube-apiserver",status_class="5xx"})
      /
      sum(status_class:apiserver_request_total:rate3d{job="kube-apiserver"})
    "labels":
      "job": "kube-apiserver"
    "record": "status_class_5xx:apiserver_request_total:ratio_rate3d"
```

### CODE REVIEW

**Comment by metalmatze** [comment]
We should probably look at this a bit more too:
https://github.com/kubernetes/community/blob/master/sig-scalability/slos/slos.md

**Comment by metalmatze** [comment]
Discussed with @brancz that we probably want this separate and not in the mixin directly?! Maybe it needs to be explicitly enabled?

**Comment by brancz** [comment]
I think we’re running the risk that everyone has different expectations for their kubernetes clusters. That said I’m willing to try this out as is and change if needed.

**Comment by metalmatze** [comment]
> I think we’re running the risk that everyone has different expectations for their Kubernetes clusters. 

That's why I put the specific SLO configuration at the top of `config.libsonnet`. :blush:

**Comment by brancz** [comment]
Let's see what @tomwilkie and or @csmarchbanks say, just want one more opinion.

**Comment by csmarchbanks** [comment]
I am a fan of including SLOs in the mixin as I think it would push general exposure of alerting on SLOs to more people.

**Comment by csmarchbanks** [comment]
A couple general comments:
1. Shouldn't the recording rules like `status_class:apiserver_request_total:rate5m` get rid of the `_total`? First paragraph of [recording rules best practice page].(https://prometheus.io/docs/practices/rules/#naming-and-aggregation)
1. I am not sure I like the name `status_class_5xx:apiserver_request_total:ratio_rate5m`, since that would indicate there is still a `status_class` label. Perhaps something more like `:apiserver_request:failure_ratio_rate5m`?

Those are probably comments for your SLO library more than this specific implementation.

**Comment by metalmatze** [comment]
I totally get your points on the naming of the rules. We had long discussions over at https://github.com/metalmatze/slo-libsonnet/pull/18. Ultimately it's a tradeoff between ease of use (fewer configuration) and being able to specify every detail. I'm happy to talk about all of that. That discussion is probably best done in another issue over https://github.com/metalmatze/slo-libsonnet/ and might just block merging it here.

**Comment by brancz** [comment]
Yeah I’m happy with it as is, as this is generated, I also think improvements to the generated names should happen in the slo libsonnet.

**Comment by csmarchbanks** [comment]
Yep, I agree, fine with it as is and we can improve the generated rules later.

**Comment by brancz** [comment]
Sorry looks like I introduced a conflict by merging something else. Could you rebase this?

**Comment by metalmatze** [comment]
Rebased. :)

**Comment by brancz** [comment]
Let's do this. lgtm :+1:

**Pull request merged**
