### PR TITLE
break down resource dashboards to multiple files

### PR DESCRIPTION
**Pull request by omerlh**
A small refactor to make it easier to change those dashboards.

### CODE REVIEW

**Comment by brancz** [comment]
In what way does this solve #329? As far as I can tell this only moves the dashboards to separate file not add the things suggested in that issue. I would prefer if we can keep the moving changes in separate PRs so it’s easier to review.

**Comment by omerlh** [comment]
Sure, so can we merge this first? I opened it as a draft PR and I'm now working on the actual PR that fix #329, I just wasn't sure what you'll think about the break down - but it was too hard working on the dashboards without it.

**Comment by brancz** [comment]
I prefer this breakdown I think. Happy to merge as is and then have the actual work in a separate PR.

**Comment by omerlh** [comment]
Ok, I changed the comment - ready for merge.

**Comment by brancz** [comment]
Thanks!

**Comment by dghubble** [comment]
@omerlh this seems to have deleted the StatefulSets dashboard entirely

**Comment by omerlh** [comment]
Yes sorry - I removed 2 dashboards that seems a duplication of other dashboards - pods and statefulset. I'll be happy to return them if I made a mistake.

**Comment by dghubble** [comment]
Is there an equivalent of the statefulset information in the resources dashboards? It doesn't seem like it. I'm not a statefulset user personally, but suspect this wasn't intended.

**Comment by omerlh** [comment]
I opened another PR to return it, there are some panels that indeed does not exist in the resources dashboards. It's my mistake - I looked only at the pods dashboards and notice it's the same.

I do think it worth thinking how we can merge this dashboard into the resources dashboards - ideally, trying to have as few dashboards as possible.

**Comment by brancz** [comment]
What is the actual difference with the pod dashboard? I do agree that we should just merge them.

**Comment by metalmatze** [comment]
Fully agree to merge those dashboards. I don't like how standalone they are when they can easily be integrated in the others.

**Comment by omerlh** [comment]
The statefulset dashboard contains some info about the replicas that are currently available and stuff like that - which is not exactly available on resources dashboards. We can add something generic as this is the same idea also for daemonset/deployments - maybe to the workload dashboard.

**Comment by metalmatze** [comment]
Yes, exactly. That's what I had in mind too, the workload dashboards should be good for that.

**Comment by aryandadashi** [comment]
@omerlh @brancz @metalmatze It's probably too late but we have been using pods dashboard for quite a long time in our organization (a multinational company) because it offers a summary of resources consumed in the pods in a concise way as well it shows the number of restarts. Number of restarts (crashes) is very important and I couldn't find it together with other pod dashboards. Is it ok if I create a PR and return pods dashboard?

**Pull request merged**
