### PR TITLE
dashboards/node: Fix Disk Space Usage gauge

### PR DESCRIPTION
**Pull request by s-urbaniak**
Currently, the gauge does not work if there are multiple
file systems attached to a node.
This fixes it by replacing it with a graph.

This also fixes the alignment of the cpu and memory rows.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1622387

/cc @brancz @metalmatze

### CODE REVIEW

**Comment by s-urbaniak** [comment]
for brevity, this is how the dashboard looks in f5b2bcf

image

**Comment by s-urbaniak** [comment]
and the current regression if multiple file systems are attached to a node:

image

**Comment by s-urbaniak** [comment]
and this is how it looks with a multi-filesystem node with this PR:
image

**Comment by brancz** [comment]
Makes sense. We should also work towards consolidating the nodes dashboard with the USE/node dashboard. But for now, this fixes the problem at hand.

lgtm :+1:

**Pull request merged**
