### PR TITLE
dashboards/network-usage: don't collapse rows by default

### PR DESCRIPTION
**Pull request by jan--f**
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>

Had a report about collapsed rows being unexpected.
I fail to come up with an argument for collapsing some rows, hence this proposal.

### CODE REVIEW

**Comment by brancz** [comment]
hmm I personally prefer them being collapsed by default, as otherwise I need to scroll through the entire dashboard to know what's available .. when I look at a dashboard I already know what will be interesting to look at

**Comment by jan--f** [comment]
ok, so the collapsed rows are generally less interesting? Should we maybe add them to the bottom of the dashboard then or even altogether remove them (or some of them)? In fact in some dashboards the rows in question are already at the bottom, so showing them uncollapsed should not change anything.

**Comment by brancz** [comment]
I'd say we collapse everything except memory and cpu

cc @metalmatze @csmarchbanks @paulfantom what are your thoughts?

**Comment by ArthurSens** [comment]
On dashboards by workload or by pod, one might have way too many metrics to show. Especially if the dashboard time range is too broad.

In these cases, having all rows uncollapsed can make those dashboards extremely slow or even crashes the chrome/firefox tab since it is all rendered client-side.

**Comment by jan--f** [comment]
> On dashboards by workload or by pod, one might have way too many metrics to show. Especially if the dashboard time range is too broad.
> 
> In these cases, having all rows uncollapsed can make those dashboards extremely slow or even crashes the chrome/firefox tab since it is all rendered client-side.

Sounds like we should fix those panels to not crash a tab. I'll take a look at it, @ArthurSens any chance you could open an issue for that or point me to an existing one?

**Comment by ArthurSens** [comment]
> Sounds like we should fix those panels to not crash a tab. I'll take a look at it, @ArthurSens any chance you could open an issue for that or point me to an existing one?

This is more a Grafana issue than mixin's I think, so there is not much we can do about it 😬. Grafana renders everything that is uncollapsed on every refresh, it can be way too slow when dealing with big amounts of data.

At your PR description, I see:
> I fail to come up with an argument for collapsing some rows, hence this proposal.

So I've just answered with my point of view about why some rows need to be collapsed :)

**Comment by jan--f** [comment]
> At your PR description, I see:
> 
> > I fail to come up with an argument for collapsing some rows, hence this proposal.
> 
> So I've just answered with my point of view about why some rows need to be collapsed :)

Yep and thanks for that. 

> This is more a Grafana issue than mixin's I think, so there is not much we can do about it . Grafana renders everything that is uncollapsed on every refresh, it can be way too slow when dealing with big amounts of data.

We could look into limiting the number of series that are drawn in a panel, hence my question regarding an issue or data which panels cause this under which conditions. Having a panel that tries to draw 1000s of series is probably not very useful anyway.
So any additional input would be much appreciated.

**Comment by paulfantom** [comment]
Quoting "Information Dashboard Design" by Stephen Fay:

> The information should appear on a single screen, entirely available within the viewer's eye span so it can all be seen at once, at a glance. If the viewer must scroll around to see all information, it is no longer a dashboard. [...] The objective is to have the most important information readily and effortlessly available, so the viewer can quickly absorb what he or she needs to know.

That said I am personally not a fan of dashboards in which I need to scroll down to figure out anything. I like the ones that present me with an overview with a possibility to drill down into specifics (either via linking to another dashboard or expanding rows). Such an approach also shouldn't put much strain on grafana itself as there is a limited amount of space on the screen and a limited number of panels.

For our use-cases, I think we should collapse everything apart from the most critical information in the dashboard. In the case of networking dashboards I would collapse all apart from "Current Bandwidth", but I am not sure if the panel type we use for it is the best to present that data.

**Comment by brancz** [comment]
I agree with @paulfantom.

**Comment by jan--f** [comment]
Sounds good, thanks everyone!

@ArthurSens if you have any more input on the scalability issue of (some) of these panels, I'd appreciate it. This is something we should fix.

**Pull request closed without merging**
