### PR TITLE
Interval variable fixed

### PR DESCRIPTION
**Pull request by dimm0**
$interval variable changed to $__interval

### CODE REVIEW

**Comment by brancz** [comment]
Related to https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/372

**Comment by brancz** [comment]
@povilasv @dimm0 I guess now we could get rid of the duplicate/unused `$interval` variable defined in each of the dashboards?

**Comment by dimm0** [comment]
I don't see any in this project...

**Comment by povilasv** [comment]
I think @brancz  is talking about the `intervalTemplate` variable:

grep -r 'intervalTemplate' *          
```
dashboards/resources/namespace.libsonnet:    local intervalTemplate =
dashboards/resources/namespace.libsonnet:      ) + { tags: $._config.grafanaK8s.dashboardTags, templating+: { list+: [intervalTemplate, clusterTemplate, namespaceTemplate] }, refresh: $._config.grafanaK8s.refresh },
dashboards/resources/pod.libsonnet:    local intervalTemplate =
```

And yup we need to get rid of it.

**Pull request merged**
