### PR TITLE
Contribute grafana dashboards

### PR DESCRIPTION
**Pull request by povilasv**
Some changes from my stuff include: 

- added tags and prefix for dashboards
- added kube-proxy selector
- renamed Dashboards
- removed Kube prefix

## kube-proxy:
- Added dash for network programming rate + latency
- Switched to seconds metrics instead of microseconds.

## kube-scheduler:
- switched to seconds metrics instead of microseconds.
- Added scheduler_volume_scheduling_duration_seconds_bucket
- Latency rate 5m instead of 10h
- Added sheduling rate

## kube-controller-manager:
- Remove deprecated work queue metrics
- Add new workqueue metrics.

## kube api server
- Changes in etcd cache duration, went from summary to buckets.
- Fixed cache latency -> cache duration title
- apiserver_request_count > apiserver_request_total
- apiserver_request_latencies_bucket > apiserver_request_duration_seconds_bucket
- Admission controller queue -> generic work queue metrics.
- etcd_helper_cache_entry_count ->  etcd_helper_cache_entry_total

## kubelet
- Changed a lot of metrics to use _second instead of _microsecond
- Use histogram `kubelet_cgroup_manager_duration_seconds_bucket` instead of summary
- Use histogram `kubelet_pleg_relist_duration_seconds_bucket` 
- Add PLEG relist interval
- `kubelet_runtime_operations` -> `kubelet_runtime_operations_total `
- Add rate `storage_operation_errors_total`
- Removed kubelet_network_plugin_operations_latency_microseconds_count and kubelet_network_plugin_operations_latency_microseconds
- Add instance label everywhere, because now there is histograms for everything we can have an aggregate view!
- Add actual volume count
- Add desired volume count
- Added config error rate
- Remove volume table, as there is no more metrics? (maybe issue with kind)

### CODE REVIEW

**Comment by metalmatze** [comment]
On Kubernetes Slack in #monitoring-mixins we agreed to move these dashboards to Kubernetes 1.14 before merging.

**Comment by povilasv** [comment]
Kube proxy on kind v1.14.1:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-05-14T01:43:56Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by povilasv** [comment]
Kube-Scheduler:

**Comment by povilasv** [comment]
Kube controller manage:

**Comment by povilasv** [comment]
Kube api server
ETCD cache duration doesn't show because cache is 0 in my kind cluster

**Comment by povilasv** [comment]
Leaving Kubelet for tommorow as it doesn't work at all :)

This is how menu looks:

**Comment by metalmatze** [comment]
> Leaving Kubelet for tommorow as it doesn't work at all :)
> 
> This is how menu looks:
> 
> 

All of the above look really good. Looking forward to merging them!
Just for consistency: I don't think you need to prefix those dashboard names twice.
```diff
- Kubernetes / Kube API server
+ Kubernetes / API server
```
That should be fine.

**Comment by povilasv** [comment]
@metalmatze Done, I've also renamed the files

```
-rw-r--r-- 1 povilasv povilasv 35925 May 17 06:03 apiserver.json
-rw-r--r-- 1 povilasv povilasv 34874 May 17 06:03 controller-manager.json
-rw-r--r-- 1 povilasv povilasv 26422 May 17 06:03 k8s-cluster-rsrc-use.json
-rw-r--r-- 1 povilasv povilasv 26293 May 17 06:03 k8s-node-rsrc-use.json
-rw-r--r-- 1 povilasv povilasv 44314 May 17 06:03 k8s-resources-cluster.json
-rw-r--r-- 1 povilasv povilasv 28509 May 17 06:03 k8s-resources-namespace.json
-rw-r--r-- 1 povilasv povilasv 30336 May 17 06:03 k8s-resources-pod.json
-rw-r--r-- 1 povilasv povilasv 30165 May 17 06:03 k8s-resources-workload.json
-rw-r--r-- 1 povilasv povilasv 31309 May 17 06:03 k8s-resources-workloads-namespace.json
-rw-r--r-- 1 povilasv povilasv 62919 May 17 06:03 kubelet.json
-rw-r--r-- 1 povilasv povilasv 40564 May 17 06:03 nodes.json
-rw-r--r-- 1 povilasv povilasv 16180 May 17 06:03 persistentvolumesusage.json
-rw-r--r-- 1 povilasv povilasv 18830 May 17 06:03 pods.json
-rw-r--r-- 1 povilasv povilasv 32995 May 17 06:03 proxy.json
-rw-r--r-- 1 povilasv povilasv 26116 May 17 06:03 scheduler.json
-rw-r--r-- 1 povilasv povilasv 27220 May 17 06:03 statefulset.json
```

**Comment by povilasv** [comment]
Kubelet

**Comment by povilasv** [comment]
TODO: 

- Maybe add scheduling rate?
- Fix some places we still have microseconds
- for next metric overhaul:

job_adds > job_add_total
job_queue_latency - > job_queue_latency_secnods
job_work_duration -> job_work_duration_seconds
and maybe move this stuff to buckets instead of summaries.

**Comment by povilasv** [comment]
Controller manager after fixes

**Comment by povilasv** [comment]
API server after fixes:

**Comment by povilasv** [comment]
Scheduler fixes:

**Comment by povilasv** [comment]
@metalmatze @brancz PTAL :)

**Comment by povilasv** [comment]
Super glad to do a v2 of this :D although it involved **a lot** of manual work, but as they say repetition is the mother of learning :dancing_men:

**Comment by metalmatze** [comment]
This is super awesome and thanks for putting all the work into it. :tada: 
To not make things even more complicated we want to merge this now and then create follow up PRs.

I'll create an issue with a TODO list of things we want to improve about these in the future.

Thanks again!

**Comment by povilasv** [comment]
@metalmatze cool, let me now I might help :)

**Pull request merged**
