### PR TITLE
add xfs type to the disk related grafs in use dashboards

### PR DESCRIPTION
**Pull request by nrobert13**

### CODE REVIEW

**Comment by tomwilkie** [comment]
Might be worth pulling this matcher out into config, to support more esoteric filesystems, and ensure they stay consistent?

**Comment by s-urbaniak** [comment]
@tomwilkie @nrobert13 I am working on exactly this right now, pulling the matcher as a simple array into `config.libsonnet` (and also fixing one unrelated query) as there are very many references to the same set of filesystems in many expressions.

**Comment by s-urbaniak** [comment]
@nrobert13 having said that, feel free to continue with the factoring if you wish.

**Comment by nrobert13** [comment]
@s-urbaniak will do once your pr gets merged so I can use fstypeSelector, or you can do it in your PR and we just close this...

**Comment by s-urbaniak** [comment]
@nrobert13 just fyi, #64 has been merged, including factoring filesystem types into a global array. Is the FS support covered by that? Otherwise I believe we can close this PR in favor of #64.

**Comment by nrobert13** [comment]
@s-urbaniak that's perfect. thank you! we can close this.

**Pull request closed without merging**
