### PR TITLE
Remove AggregatedAPIDown alert

### PR DESCRIPTION
**Pull request by povilasv**
FIX https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/397

Let's remove this until it's fixed in Kubernetes.

https://github.com/kubernetes/kube-aggregator/issues/23

### CODE REVIEW

**Comment by brancz** [comment]
cc @p0lyn0mial

**Comment by brancz** [comment]
@p0lyn0mial just reminded me of https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/358

What I think we should do is only remove this in the latest release branch, but keep it in master.

**Comment by lilic** [comment]
Yes 👍 0.3 sgtm, 0.4 is 1.18, we should maybe document that somewhere? https://github.com/kubernetes-monitoring/kubernetes-mixin#releases :D

**Comment by povilasv** [comment]
So I'm super confused which branch points to what kubernetes release, as I though 0.4 is for 1.16+ as per https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/379#issuecomment-615096334

**Comment by povilasv** [comment]
Closing this PR in favor of  https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/406 and https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/407

**Comment by lilic** [comment]
We actually do in kube-prometheus. :)

**Comment by den-is** [comment]
But compatibility matrix states that k8s 1.18 support is enabled starting from v0.5
https://github.com/coreos/kube-prometheus#kubernetes-compatibility-matrix

**Comment by povilasv** [comment]
@lilic any chance you want to do the same for this repo? I'm still a bit confused on the relationship of the versions to this repo.

**Pull request closed without merging**
