### PR TITLE
Adhere to monitoring mixins annotation guidelines

### PR DESCRIPTION
**Pull request by paulfantom**
* replaced `message` annotation field with `description`
* added simple `summary` field

Guidelines: https://monitoring.mixins.dev/#guidelines-for-alert-names-labels-and-annotations

/cc @brancz @beorn7

### CODE REVIEW

**Comment by paulfantom** [comment]
Setting to WIP as I need to adjust tests

**Comment by paulfantom** [comment]
Fixed tests :) Ready for review.

**Comment by brancz** [comment]
I'd say let's start with this and iterate.

**Comment by beorn7** [comment]
Thanks for this.

**Pull request merged**
