### PR TITLE
alerts when an aggregation API is down or it reports errors

### PR DESCRIPTION
**Pull request by p0lyn0mial**
back ports https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/355

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
@lilic @brancz is this branch (release-0.3) meant to be used with a specific Kuberenetes release?

I'm asking because recently a person that uses Kube in `v1.15.10` version observed these alerts constantly firing due to the lack of https://github.com/kubernetes/kubernetes/pull/87778 fix.

**Comment by brancz** [comment]
`release-0.3` is 1.17+

**Comment by p0lyn0mial** [comment]
@brancz ups, the fix (https://github.com/kubernetes/kubernetes/pull/87778) will be part of `1.18+` release, what now?

**Pull request merged**
