### PR TITLE
Remove duplicate rule 'namespace:container_cpu_usage_seconds_total:sum_rate'

### LINKED ISSUE #230: Recording rule generating "duplicate sample for timestamp" errors
There are (at least) 2 recording rules producing the same metric name (`namespace:container_cpu_usage_seconds_total:sum_rate`):

https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/3596bcd93d15aad44a8403314c37c2ede04e3d8d/rules/rules.libsonnet#L7-L12

https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/3596bcd93d15aad44a8403314c37c2ede04e3d8d/rules/rules.libsonnet#L30-L39

This generates transient errors in the Prometheus logs when some pods don't have the `name` label. And even if all pods had a `name` label, it would still generate inconsistent data as the label set would be heterogeneous (eg the latter rule generates samples with the `label_name`label while the former doesn't).

```
level=debug ts=2019-07-30T08:12:25.748Z caller=manager.go:542 component="rule manager" group=k8s.rules msg="Rule evaluation result discarded" err="duplicate sample for timestamp" sample="{__name__=\"namespace:container_memory_usage_bytes:sum\", namespace=\"openshift-monitoring\"} => 2516475904 @[1564474345729]"
level=debug ts=2019-07-30T08:12:25.748Z caller=manager.go:542 component="rule manager" group=k8s.rules msg="Rule evaluation result discarded" err="duplicate sample for timestamp" sample="{__name__=\"namespace:container_memory_usage_bytes:sum\", namespace=\"openshift-marketplace\"} => 211025920 @[1564474345729]"
level=debug ts=2019-07-30T08:12:25.748Z caller=manager.go:542 component="rule manager" group=k8s.rules msg="Rule evaluation result discarded" err="duplicate sample for timestamp" sample="{__name__=\"namespace:container_memory_usage_bytes:sum\", namespace=\"openshift-image-registry\"} => 27029504 @[1564474345729]"
level=debug ts=2019-07-30T08:12:25.748Z caller=manager.go:542 component="rule manager" group=k8s.rules msg="Rule evaluation result discarded" err="duplicate sample for timestamp" sample="{__name__=\"namespace:container_memory_usage_bytes:sum\", namespace=\"openshift-cluster-node-tuning-operator\"} => 246497280 @[1564474345729]"
level=debug ts=2019-07-30T08:12:25.748Z caller=manager.go:542 component="rule manager" group=k8s.rules msg="Rule evaluation result discarded" err="duplicate sample for timestamp" sample="{__name__=\"namespace:container_memory_usage_bytes:sum\", namespace=\"openshift-machine-config-operator\"} => 204845056 @[1564474345729]"
level=warn ts=2019-07-30T08:12:25.748Z caller=manager.go:554 component="rule manager" group=k8s.rules msg="Error on ingesting results from rule evaluation with different value but same timestamp" numDropped=5
```

Issue already reported here: https://github.com/coreos/kube-prometheus/issues/134

### PR DESCRIPTION
**Pull request by simonpasquier**
Closes #230

### CODE REVIEW

**Comment by metalmatze** [comment]
Do we even need this with labels? But if so, lgtm.

**Comment by brancz** [comment]
`label_name` was an artifact of Grafana's setup. It should be removed.

**Comment by simonpasquier** [comment]
So the rule should be removed altogether? https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/230#issuecomment-517286638

**Comment by brancz** [comment]
Just the part about the `label_name` label. If I recall correctly that will result in a duplicate recording rule, so that should be de-duplicated :)

**Comment by simonpasquier** [comment]
PR updated to remove the duplicate rule that joined on `kube_pod_labels`.

**Comment by brancz** [comment]
lgtm :+1:

**Pull request merged**
