### PR TITLE
Added script which checks metrics in prometheus from Grafana Dashboard

### PR DESCRIPTION
**Pull request by witold-gren**
Added script which checks metrics in prometheus and which are use by Grafana dashboard.

### CODE REVIEW

**Comment by povilasv** [comment]
Agree, also I think maybe we can docker is atleast? The build, the lint, etc.

**Comment by cewood** [comment]
> Also I think maybe we can dockerize atleast? The build, the lint, etc, provide an image people can run

I was thinking this as well, could definitely add this if that would be helpful?

**Comment by witold-gren** [comment]
The script was prepared without any external packages so it should work wherever python3 is installed. I didn't check it but it should work since python 3.4.

**Comment by metalmatze** [comment]
Very nice. While I think it's nice it's uses are limited if it doesn't work in CI. :thinking: Maybe we can somehow integrate this with a CI dataset. I don't know. hm.

**Comment by brancz** [comment]
I think this is super useful, but I think this might be best as a separate project actually. Happy to promote it in the readme though as a form of "conformance".

**Comment by cewood** [comment]
> I think this is super useful, but I think this might be best as a separate project actually. Happy to promote it in the readme though as a form of "conformance".

To clarify, were you suggesting to host it under the `kubernetes-monitoring` org as a separate project, or you think we should host it ourselves separately?  cc/ @brancz

**Comment by metalmatze** [comment]
It's fine to have it in some repository. I wouldn't want to add more repositories to this org, actually.

**Comment by brancz** [comment]
Agreed with @metalmatze

**Comment by witold-gren** [comment]
Thank's for responses. We will prepare separate repository for this tool. If we finish publish script then we will sent information to you.

**Comment by metalmatze** [comment]
Thanks so much! In the meantime I'll close this, as a follow up should be new PR :blush:

**Pull request closed without merging**
