### PR TITLE
Add $cluster variable to some dashs

### PR DESCRIPTION
**Pull request by anfouque**
Hi,

After building, the $cluster variable was missing from controller manager and scheduler dashboards. I went trough both libsonnet and made a few changes so the variable can show up in both of them.

### CODE REVIEW

**Comment by metalmatze** [comment]
Do other maintainers know if this was on purpose or we just missed it?

**Comment by brancz** [comment]
cc @csmarchbanks

**Review by csmarchbanks — COMMENTED** [review]
This looks reasonable to me, but I don't actually have any k8s clusters to test it on right now.

My guess is it just wasn't thought about when the dashboards were created, I wonder if there should be a checklist item in pull requests to make sure there are cluster labels on new dashboards/panels?

**Comment by brancz** [comment]
In my experience, this type of thing can really only be prevented effectively with static analysis type of things. Either way, I'm happy to move forward with this.

**Pull request merged**
