### PR TITLE
Add kube pod resource limits aggregation

### PR DESCRIPTION
**Pull request by fengyehong**

### CODE REVIEW

**Comment by paulfantom** [comment]
What's the story behind adding those recording rules? I don't see any issue raised and those are not used by the project.

**Comment by fengyehong** [comment]
When checking resource status of a namespace or a whole cluster, I think aggregation status on both `requests` and `limits` are very useful. 

Before this we already have aggregation on requests `namespace_(cpu|memory):kube_pod_container_resource_requests:sum`, By having `namespace_(cpu|memory):kube_pod_container_resource_requests:sum` we can:

1. know the maximum resources can be used in real runtime
2. by comparing `sum(namespace_(cpu|memory):kube_pod_container_resource_limits:sum)` with cluster total resources, we have an indicator on the possibility resource competition can happen in runtime
3. by comparing `namespace_(cpu|memory):kube_pod_container_resource_requests:sum{namespace="foo"}` and `namespace_(cpu|memory):kube_pod_container_resource_limits:sum{namespace="foo"}`, we have an indicator or how "burstable" a namespace can be

Personally I want to use the second item, I think its a good monitoring dimension on cluster resource status.

**Comment by paulfantom** [comment]
I don't say those queries aren't useful for the administrator. However, I didn't see why they should be included in this project as recording rules. Especially considering that recording rules used neither in alerts nor in dashboards tend to go stale and only increase the load on prometheus server.

**Comment by fengyehong** [comment]
I updated some of the dashboards to use it. This should make the dashboard load faster if we have thousands of pods running in cluster.

**Comment by fengyehong** [comment]
I updated some of the dashboards to use it. This should make the dashboard load faster if we have thousands of pods running in cluster.

**Comment by PhilipGough** [comment]
@paulfantom this change is related since the update to #629 and could probably close #629 with some minor additions

@fengyehong if you have a look at the linked PR, I am also dividing by the recording rules also to filter out completed and failed pods

**Comment by fengyehong** [comment]
@PhilipGough Sure, I added your parts.

**Review by paulfantom — APPROVED** [review]
Thank you! :100:

**Pull request merged**
