### PR TITLE
Clarify node template variable in kubelet dash

### PR DESCRIPTION
**Pull request by hjet**
Can use `node` as well..

### CODE REVIEW

**Comment by arajkumar** [comment]
lgtm. @hjet better squash your commits into one.

**Comment by hjet** [comment]
thanks @arajkumar, done!

**Comment by povilasv** [comment]
I think this was introduced in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/703/files

cc @rgeyer

Any reason you folks landed on "Data Source" label?

**Comment by hjet** [comment]
@povilasv I think that's referring to a different line than this change (see [this](https://github.com/kubernetes-monitoring/kubernetes-mixin/blame/master/dashboards/kubelet.libsonnet#L324))

i think this is just a bug

**Review by povilasv — APPROVED** [review]

**Pull request merged**
