### PR TITLE
Remove Kubelet certificate expiration alerts

### PR DESCRIPTION
**Pull request by simonpasquier**
~~The `KubeClientCertificateExpiration` alert isn't really actionable for a cluster admin since it doesn't pinpoint which workload is triggering the issue.~~

The `Kubelet*CertificateExpiration` alerts overlap with `KubeletClientCertificateRenewalErrors` and    `KubeletServerCertificateRenewalErrors` alerts which don't require to adjust the expiration threshold to match with the cluster settings.

cc @paulfantom

### CODE REVIEW

**Comment by brancz** [comment]
I don't think I agree with the premise of let's say the lack of more logs to understand what is causing this to fire is a reason to remove this entirely. I feel we should instead add logs to the apiserver that describes what is causing this, no?

**Comment by simonpasquier** [comment]
@brancz is your comment specifically about the removal of `KubeClientCertificateExpiration` alerts?

**Comment by povilasv** [comment]
I don't agree either, I had `KubeClientCertificateExpiration` firing then kubeadm provisioned certificate (the one which initially gives you cluster admin) was getting close to expiry, non other alerts where firing, so I think we need to keep it.

**Comment by brancz** [comment]
I meant my argument in regards to both

**Comment by simonpasquier** [comment]
ack, closing then :)

**Comment by brancz** [comment]
Similar note: https://github.com/prometheus-operator/kube-prometheus/issues/881

If nothing else I think it's worth talking to apimachinery and having some logging added about this.

**Pull request closed without merging**
