### PR TITLE
WIP:alerts/resource_alerts.libsonnet: Add namespace selector to CPUThrottlingHigh

### PR DESCRIPTION
**Pull request by lilic**

### CODE REVIEW

**Comment by lilic** [comment]
Not sure this is the correct thing to do it. 🤔

**Comment by povilasv** [comment]
Why do we need that? Why not just add namespace selector to `cpuThrottlingSelector` variable?
you could do `cpuThrottlingSelector="job="job",namespace="namespace"`.

**Comment by brancz** [comment]
Agreed with @povilasv.

**Comment by lilic** [comment]
Thanks! And sorry about that, still new to this jsonnet stuff :)

**Pull request closed without merging**
