### PR TITLE
switched alerts from 1h to 15m

### PR DESCRIPTION
**Pull request by mitchellmaler**
Updated alert duration from 1h to 15m to allow getting them quicker. Let me know if there are any more that make more sense to change or if I should switch any back.

### CODE REVIEW

**Comment by brancz** [comment]
I didn't realize you meant multiple alerts. Generally this seems ok to me, but should have a second look by @metalmatze and @csmarchbanks .

**Comment by brancz** [comment]
I recall there being another PR that tried something similar.

**Comment by metalmatze** [comment]
Unable to find the issue or PR, but we've definitely discussed this and settle for the current values IIRC. If you disagree, I  think we said to override this with jsonnet. Not 100% sure though.

**Comment by mitchellmaler** [comment]
@metalmatze I am perfectly fine overriding these values instead if possible. Is there documentation on how to change the duration with jsonnet?

**Comment by csmarchbanks** [comment]
Perhaps this PR? https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/196

I think this PR looks ok, all those alerts having a shorter `for` seems like a good idea. I do think we should have a good and easy way of overriding alerts for mixins generally.

**Comment by brancz** [comment]
I think changing these for conditions should be no problem. Let's try it and reassess should it not work out well.

**Pull request merged**
