### PR TITLE
alerts/resource_alerts.libsonnet, runbook.md: Reduce KubeQuotaExceeded severity and adjust threshold

### LINKED ISSUE #441: KubeQuotaExceeded fires even if quota is not exceeded
From https://bugzilla.redhat.com/show_bug.cgi?id=1846707:

On OSD (OpenShift Dedicated) we create a ResourceQuota [1] for logging that is at 100% of what we allow allocating for logging PVCs.  The KubeQuotaExceeded alert fires if quota is at or above 90% allocated.  This means the alert is always firing.  The name of the alert implies quota is exceeded and we are getting concerned queries from customers regarding this alert firing in the cluster.  We don't think allocating less than 90% of the quota is the right answer and request the expr for this alert be adjusted.

We are tracking a workaround for our alerting [2] that will fire if quota is actually exceeded.  The expr would become:

```
kube_resourcequota{job="kube-state-metrics",namespace="(openshift-.*|kube-.*|default|logging)",type="used"} / ignoring(instance, job, type) (kube_resourcequota{job="kube-state-metrics",namespace="(openshift-.*|kube-.*|default|logging)",type="hard"} > 0) > 1 
```

/cc @jewzaam

### PR DESCRIPTION
**Pull request by RiRa12621**
This fixes #441 according to my proposal made in the comments https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/441#issuecomment-647032780

### CODE REVIEW

**Comment by RiRa12621** [comment]
Converted to draft to allow some time for discussion

**Comment by brancz** [comment]
I didn't realize that this would be the first `info` severity alert here. I think we should first discuss this with the other maintainers. To unblock this though I think it would be ok to keep this alert warning severity being strictly over quota as in`> 1`.

**Comment by RiRa12621** [comment]
I'd wait for the conversation to finish in the actual issue before adjusting.
This was mainly to facilitate my proposal hence i also made it a `draft`

Makes total sense that it needs a wider discussion with the maintainers since it's introducing a new level

**Comment by brancz** [comment]
cc @csmarchbanks @metalmatze @tomwilkie @povilasv @s-urbaniak 

@beorn7's option would be interesting as well I think.

Thoughts on introducing `severity: info` which is expected to be inhibited, unless a warning or critical alert is firing?

**Comment by beorn7** [comment]
I usually advertise info-level alerts as alerts that do not cause any notifications sent out to anyone (except perhaps a catch-all sink for archive purposes. Those alerts are supposed to be looked at if you want to see what is "out of the ordinary" while looking for possible reasons for a real issue, or if you just want to know if anything is slightly off for any other reason (e.g. just before performing a risky operation or before leaving for the weekend).

From that perspective, there doesn't have to be inhibition.

And yeah, it sounds like it would be the right level here.

**Comment by s-urbaniak** [comment]
I am in line with the rationale outlined in https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/441#issuecomment-647032780 and lowering severity to `info` makes sense to me here too.

**Comment by brancz** [comment]
Sounds like as long as we document the expectations in the readme, we can move ahead with this.

**Comment by RiRa12621** [comment]
I will extend this wie an addition to the readme later or tomorrow

**Comment by RiRa12621** [comment]
I'm not entirely sure if that's the right place and happy about any comments and remarks.
I have now also adjusted the name like i propose and made this "open for review"

**Comment by dudicoco** [comment]
@RiRa12621 @metalmatze @brancz I don't understand the rationale behind setting this rule as `info`.

If the quota is reached this could mean new pods cannot be launched in within a namespace, which in turn can cause havoc within the namespace if hpa/cronjobs/other means of dynamically launching pods is used.
To me this seems like a critical alert.

**Pull request merged**
