### PR TITLE
Update jb install command

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Review by metalmatze — APPROVED** [review]
Nice! Thanks!

**Comment by metalmatze** [comment]
Whoever sees this next, please merge since the CI is just starting now... 
Still no "merge on green" button with GitHub :roll_eyes:

**Comment by ArthurSens** [comment]
> Whoever sees this next, please merge since the CI is just starting now... 
> 
> Still no "merge on green" button with GitHub :roll_eyes: 

GitHub's automerge feature is actually the "merge on green button" 😅

**Comment by metalmatze** [comment]
I just enabled this for this repository. Is that the thing?
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request

**Comment by ArthurSens** [comment]
Yep, for pull requests with CI still running, you'll see a button "Enable auto-merge". If you enable it for a particular pull request, then it gets merged after all CI checks marked as "Required" become green 👍

**Pull request merged**
