### PR TITLE
Cherry-pick: Change cause based alerts to warning

### PR DESCRIPTION
**Pull request by RiRa12621**
Cherry-picking #402 so we have the possibility to have this as part of OCP 4.5.z

### CODE REVIEW

**Comment by RiRa12621** [comment]
the test is expecting a critical for kubepodnotready https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/9992325a3429a8975caa95bf0ead13804f76fd47/tests.yaml#L263
in master those tests are expecting `warning` already
I don't want to make merging master into release-0.4 harder than it has to be so i am not sure about cherrypicking the PR that brought those warning level tests to master as the commit is pretty big 
https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/417/files
I think I will need some guidance on how to best proceed with this

**Comment by brancz** [comment]
Just do an extra commit fixing it I would say.

**Comment by metalmatze** [comment]
This seems fine. :)

**Comment by RiRa12621** [comment]
This took me significantly longer than i thought, sorry about that.
Tests are passing now, it was just one that was off.

**Review by povilasv — APPROVED** [review]

**Pull request merged**
