### PR TITLE
alerts: add optional selector for CPUThrottlingHigh

### PR DESCRIPTION
**Pull request by andrestc**
This PR adds an optional selector used for the CPUThrottlingHigh alert.
The selector can be used to disable the alert on some noisy namespaces.

### CODE REVIEW

**Comment by metalmatze** [comment]
Not that I would disable this alert for certain namespace myself, but if people want this I would be fine with adding this. What do you think @gouthamve @brancz?

**Comment by gouthamve** [comment]
I want this so LGTM :+1: :)

**Comment by brancz** [comment]
lgtm

**Comment by paskal** [comment]
This alert in my case have 3-6 real fires and 1 ghost one, with just `alertname="CPUThrottlingHigh" severity="warning"` in tags. Did someone saw the same? How to troubleshoot this one?
I don't know if that's related to this very change, or just was there all the time (4 months): I found out after rules update in https://github.com/helm/charts/pull/9516.

**Comment by paskal** [comment]
UPD: sorry, it was related to deploying prometheus-operator without linked modules (`kube-state-metrics`, `prometheus-node-exporter`) - my bad.

**Pull request merged**
