### PR TITLE
rules: remove duplicate namespace:container_memory_usage_bytes:sum

### PR DESCRIPTION
**Pull request by s-urbaniak**
cc @brancz @LiliC @paulfantom

### CODE REVIEW

**Comment by brancz** [comment]
This is an artifact from the initial creation of the kubernetes mixin. This is a convention from Grafana. 

FYI @tomwilkie @gouthamve @beorn7

**Comment by brancz** [comment]
lgtm

**Comment by beorn7** [comment]
I don't have history on the "convention from Grafana". But this summing by pod label is also done in a few other rules. I guess we should revisit this eventually and find a consistent naming and aggregation scheme.

**Comment by brancz** [comment]
Aggregating by the “name” label is a best practice not everyone follows thus this rule does more harm than use in the kubernetes-mixin (we discovered this particular one because the time series this is written into doesn’t quite follow best practices so we had duplicates). We’ve had cases like this before and Tom asked us to just ping all of you should we remove rules like this so you can add it to your set of rules.

Yes you’re absolutely right, if there are more of these then we should remove all of the ones that aggregate by the name label.

**Pull request merged**
