### PR TITLE
KubeJob alerts message should use exported_job not job label

### PR DESCRIPTION
**Pull request by jdbaldry**

### CODE REVIEW

**Comment by tomwilkie** [comment]
Generally frown upon the used of exported_, but job here is wrong too. We should probably add some label rewrite rule or even fix KSM

**Comment by jdbaldry** [comment]
Yeah seems like usually the labels is $labels.<resource> but since it is a "job" that clashes with the existing job="KSM" label.

**Comment by StevenACoffman** [comment]
@jdbaldry Now that kubernetes/kube-state-metric#487 landed, should this change to `job_name`?

**Comment by brancz** [comment]
kube-state-metrics v1.4.0 final has been released, I'd say we give this a month or so to give people a chance to realize that this release has happened and then merge this.

**Comment by metalmatze** [comment]
This has been a month.
Would you mind rebasing this, @jdbaldry?
Maybe we can merge this in the next days.
Thanks

**Comment by metalmatze** [comment]
Would you mind rebasing again? Please leave a comment afterwards. Then we can merge this. :blush:

**Comment by jdbaldry** [comment]
It's been a while and that's my fault. I'm not sure this PR is still relevant so I'm going to close it. Happy to reopen and rebase if it's still desired though :)

**Pull request closed without merging**
