### PR TITLE
dashboards/network-usage: swap singlestat to bar graph in network-by-pod dashboard

### PR DESCRIPTION
**Pull request by paulfantom**
Information presented in singlestat panel is a sum for the whole namespace and this information is already presented in Cluster view.

This is an attempt to start unifying networking dashboards so a proper drill-down is possible. We can have a high-level Cluster overview from which we could go to Namespace and then to each Pod. I believe that was the initial vision behind splitting into multiple dashboards (@brancz correct me if I am wrong).

Dashboard panel after changes:
Screenshot_20210421_133506

### CODE REVIEW

**Comment by brancz** [comment]
Without seeing the entire dashboard, is there a reason why we're not just showing a line graph of data and the table showing the current value? I feel we would be using the available screen real estate much more effectively.

**Comment by paulfantom** [comment]
I wasn't thinking about it yet and I first tried to unify all 5 dashboards so they look similar. However, this is a good idea to change how we present the information here.

---

Side question - why do we even have `Kubernetes / Networking / Namespace (Pods)` dashboard? If we allow selecting `Include All option` and `Multi-value` in a pod selector in `Kubernetes / Networking / Pod` dashboard we essentially duplicate the whole `Kubernetes / Networking / Namespace (Pods)` one.

A 2 minute video (basically brain dump) how I think those dashboards should work (regardless of which panel types we will choose to represent data): https://youtu.be/1PZJ96vmpe4. Sorry for the awful screen flickering :(

**Comment by paulfantom** [comment]
Thinking about it more, what if we remove the table completely, as the data in it is already presented in a better way in other charts, and leave bar graphs. Bar graphs are good for "current" values as they neatly show everything without having problems with overlaying lines. 

I am thinking sth like:
Screenshot_20210421_153317

**Comment by brancz** [comment]
I like your thought a lot. The only thing I would want to make sure we are retaining is the ability to drill down, even if all that means is to click on a pod within the dashboard and it gets selected in the dropdown. Cherry on top if you could press CTRL to select multiple for the compare functionality, but not strictly necessary I think.

**Comment by paulfantom** [comment]
Drill down is preserved (and a bit improved). However, it works a bit differently than what you described - it works only by selecting one or more pods in the dropdown. I would love if we could select series in panel and either allow linking to next dashboard or populate dropdown accordingly, but I didn't found such option in grafana :(

**Comment by brancz** [comment]
hmm .. this should be possible with tables though, no?

**Comment by paulfantom** [comment]
> this should be possible with tables though

Aaaah, so that's how those are supposed to be used. TIL :) To be fair this isn't the greatest UX. I'll play around with it though to keep this functionality.

**Pull request closed without merging**
