### PR TITLE
Added Namespace level Storage metrics [Ready for review] 

### PR DESCRIPTION
**Pull request by anmolsachan**
Issue: #123 

Signed-off-by: Anmol Sachan <anmol13694@gmail.com>

### CODE REVIEW

**Comment by anmolsachan** [comment]
Most of the metrics in this PR are based on the following assumptions for a Production Cluster :

- There will be Storageclasses present backed by Some Persistent Volumes backed by Provisioner such as Gluster, Ceph, AWS-EBS, Cinder etc.
- Storage resource quotas will be defined for all the NameSpaces
- There will be no PV created directly from the mountpoints (Local-Storage) on disks since the metric kubelet_volume_stats_* do not work for them . If there is this condition, then queries using the kubelet_volume_stats_ metrics will not work for those PV's, resulting in some inconsistencies. (Eg blank values in PVC usage)
- For name-spaces like KUBE-SYSTEM, there are no PV's available by default, thus no data will be shown in those cases.
screenshot from 2019-01-21 02-00-45
screenshot from 2019-01-21 02-08-14

**Comment by anmolsachan** [comment]
> Have you seen the [PVC dashboard](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/dashboards/persistentvolumesusage.libsonnet)? Just to make sure.
> But I guess this more about having a per namespace overview, is it?
Yes, That is correct.

> Have you seen the [PVC dashboard](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/dashboards/persistentvolumesusage.libsonnet)? Just to make sure.
> But I guess this more about having a per namespace overview, is it?
Yes, That is correct. The idea is to add storage metrics to all the resource dashboards on different levels i.e Cluster, Namespace and Pod.

**Comment by anmolsachan** [comment]
@metalmatze I don't think there are any changes required in this PR as of now. Please comment if any.
@brancz Please review.

**Comment by metalmatze** [comment]
I'm not 100% sure about having this on the dashboard. However, I don't have any strong argument against it either.

**Comment by metalmatze** [comment]
I'm not 100% sure about having this on the dashboard. However, I don't have any strong argument against it either.

**Comment by anmolsachan** [comment]
Closing, as not required anymore.

**Pull request closed without merging**
