### PR TITLE
Fix api server support multi cluster

### PR DESCRIPTION
**Pull request by hd-deman**
Hi guys! I found that api-server dashboard does not work in multi-cluster mode. The reason is that the metrics from the rules do not have a cluster label

### CODE REVIEW

**Comment by brancz** [comment]
Awesome! Thank you!

**Comment by brancz** [comment]
Hmm actually I don't undestand why CircleCI didn't run. cc @paulfantom @csmarchbanks @s-urbaniak any ideas?

**Comment by paulfantom** [comment]
Seems like GitHub didn't send the payload to circleci :shrug:

**Comment by brancz** [comment]
@hd-deman could you try to amend your commit or push another empty commit to try to trigger CI?

**Comment by hd-deman** [comment]
@brancz no luck. I have allowed editing by maintainers in my fork. Fell free to play with

**Comment by paulfantom** [comment]
And now it seems CI worked :shrug:

**Comment by brancz** [comment]
Odd. In any case. Looks good, thank you! :+1:

**Pull request merged**
