### PR TITLE
Added Cluster Level Storage Metrics [Ready for review]

### PR DESCRIPTION
**Pull request by anmolsachan**
Issue: #122 

Signed-off-by: Anmol Sachan <anmol13694@gmail.com>

### CODE REVIEW

**Comment by anmolsachan** [comment]
Most of the metrics in this PR are based on the following assumptions for a Production Cluster :

- There will be Storageclasses present backed by Some Persistent Volumes backed by Provisioner such as Gluster, Ceph, AWS-EBS, Cinder etc.
- Storage resource quotas will be defined for all the NameSpaces, if not, then there might be some inconsistencies in the aggregated cluster level metrics.
- There will be no PV created directly from the mountpoints (Local-Storage) on disks since the metric kubelet_volume_stats_* do not work for them . If there is this condition, then queries using the kubelet_volume_stats_ metrics will not work for those PV's resulting in some inconsistencies.

screenshot from 2019-01-21 01-08-10
screenshot from 2019-01-21 01-08-18

**Comment by metalmatze** [comment]
See https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/140#issuecomment-456032245, as it's pretty much the same discussion.

**Comment by anmolsachan** [comment]
@metalmatze I don't think there are any changes required in this PR as of now. Please comment if any.
@brancz Please review.

Also I don't see any activity on https://github.com/kubernetes/kubernetes/issues/73019 as of now. If there are any changes required according to the CSI issue, Please let me know

**Comment by anmolsachan** [comment]
Closing, as not required anymore.

**Pull request closed without merging**
